name: template
version: 0.0.1

environment:
  sdk: ^3.10.0
  flutter: "^3.38.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  hooks_riverpod: ^3.0.3
  json_annotation: ^4.9.0
  riverpod_annotation: ^3.0.3

dev_dependencies:
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  go_router_builder: ^4.1.1
  json_serializable: ^6.11.1
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  yumnumm_lint:
    git:
      url: https://github.com/YumNumm/yumnumm_lints.git
      ref: 441526458b5117db48eec10f623895cbfa994bfe

flutter:
  uses-material-design: true
  config:
    enable-swift-package-manager: true
