name: template
version: 0.0.1

environment:
  sdk: ^3.10.0
  flutter: "^3.38.1"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  hooks_riverpod: ^3.0.3
  intl: ^0.20.2
  json_annotation: ^4.9.0
  package_info_plus: ^9.0.0
  riverpod_annotation: ^3.0.3
  slang: ^4.10.1
  slang_flutter: ^4.10.0
  talker_flutter: ^5.0.2
  talker_riverpod_logger: ^5.0.2

dev_dependencies:
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  go_router_builder: ^4.1.1
  json_serializable: ^6.11.1
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  slang_build_runner: ^4.10.0
  yumnumm_lints:
    git:
      url: https://github.com/YumNumm/yumnumm_lints.git
      ref: 441526458b5117db48eec10f623895cbfa994bfe

flutter:
  uses-material-design: true
  config:
    enable-swift-package-manager: true
